#!/usr/bin/env bash
# The CI half of the device journey: a served kernel, a database of its own, one
# tenant and one administrator, and this repository's flows at the end of them.
#
#   PK_KERNEL_IMAGE=ghcr.io/…@sha256:… scripts/e2e/mobile_ci.sh out/apk/release/app-debug-signed.apk
#   scripts/e2e/mobile_ci.sh --probe        # what this host owes, and where it was found
#
# It is platformkit's scripts/mobile_e2e.sh:128-206 adapted, copied and cited:
# the same database of its own created here and dropped in a trap that runs
# whichever step failed, the same configuration keys, the same
# `bootstrap --tenant e2e --host localhost --language pt-PT`, the same
# serve-and-wait on /health with the log printed when the process died. What is
# new here is where the binary comes from: this repository has no Go module and
# no toolchain, so it cannot `go build ./apps/platformkit`. The kernel's image is
# `gcr.io/distroless/static` with a `CGO_ENABLED=0` binary at /platformkit
# (deploy/Dockerfile), so the build is pulled by digest and lifted out with
# `docker cp` — a pinned download, not a container someone else publishes a port
# for, and the same process-on-a-port the kernel harness serves.
#
# The kernel's own README records the cost of this shape for its own copy
# (e2e/maestro/README.md:104-118: 56 identical non-comment lines, neither script
# sourcing the other, "until somebody lifts it into an owner of its own"). The
# cost is stated here rather than hidden: run.sh and this script are that copy,
# and every line either prints names the repository's own script.
#
# Nothing here is quiet. A missing tool, a missing /dev/kvm or an image named by
# nothing but a tag exits non-zero and names the missing piece; a journey that
# silently skipped would leave the coverage the README quotes looking like a
# number nobody earned.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$root"
. "$(dirname "${BASH_SOURCE[0]}")/tools.sh"

# --probe is the CI job's first step: the search above, the refusal, and the path
# of everything found. It writes the directories it searched to $GITHUB_PATH so
# the step that boots the emulator has adb and emulator on its PATH — the kernel's
# job exports PATH inside the probe step alone and re-searches in the harness,
# which works but leaves the next reader guessing which shell had which PATH.
if [ "${1:-}" = "--probe" ]; then
  pk_tools mobile_ci adb emulator maestro docker psql python3 curl keytool ||
    {
      echo "  Label: pkit-ci-linux-amd64. Either the runner image gains them or the" >&2
      echo "  journey moves to a runner that has them; it does not get skipped." >&2
      exit 1
    }
  [ -r /dev/kvm ] || {
    echo "mobile_ci: /dev/kvm is not readable, so no emulator boots here." >&2
    exit 1
  }
  # A debug keystore is generated by whoever needs one and is never committed, so
  # what is refused is the inability to have one, not its absence.
  [ -f "$HOME/.android/debug.keystore" ] || [ -w "$HOME" ] || {
    echo "mobile_ci: no debug keystore and no writable \$HOME to make one in." >&2
    exit 1
  }
  adb version | head -1
  adb devices
  emulator -version 2>/dev/null | head -3 || true
  if [ -n "${GITHUB_PATH:-}" ]; then
    for dir in $_pk_tool_paths; do printf '%s\n' "$dir" >>"$GITHUB_PATH"; done
  fi
  echo "mobile_ci: this host can run a device journey"
  exit 0
fi

apk="${1:?the verification APK to install (make apk ABIS=x86_64 PROFILE=ci && make apk-debug-sign)}"
port="${PLATFORMKIT_MOBILE_PORT:-8098}"
admin_url="${PLATFORMKIT_TEST_ADMIN_URL:?the owner connection; the job exports it}"
app_url="${PLATFORMKIT_TEST_DATABASE_URL:?the application connection; the job exports it}"
image="${PK_KERNEL_IMAGE:-}"
export PK_MOBILE_REPORT="${PK_MOBILE_REPORT:-e2e/out/report.xml}"
database="platformkit_mobile_$(date +%s)_${RANDOM}_$$"

# The pin, before anything is pulled or started. This is the kernel's argument
# (scripts/mobile_e2e.sh:31-41) with a different artifact at the end of it: a tag
# is a pointer somebody can move, and this run holds a bootstrapped administrator
# on a server the flows write through. `latest` would be somebody else's moment.
if [ -z "$image" ]; then
  echo "mobile_ci: PK_KERNEL_IMAGE names no kernel to serve. This repository cannot build the server; which build the journey runs against is the job's to name, and an unpinned download is not a test." >&2
  exit 1
fi
if [[ ! "$image" =~ @sha256:[0-9a-fA-F]{64}$ ]]; then
  echo "mobile_ci: PK_KERNEL_IMAGE has to end in @sha256:<64 hex>; $image is a tag somebody can move." >&2
  exit 1
fi
# The served kernel's vocabulary, named by the job and never guessed here: what a
# writable resource is, and which lifecycle command to run to its end. run.sh
# states the contract again to whoever runs it alone, in the same words.
for name in MODULE ENTITY KNOWN VERB VERB_FIELD VERB_TITLE; do
  [ -n "${!name:-}" ] || {
    echo "mobile_ci: $name names nothing; the job names the served kernel's vocabulary." >&2
    exit 1
  }
done
pk_tools mobile_ci docker psql python3 curl || exit 1

# A URL with the database swapped for this run's own: everything else — host,
# port, credentials, parameters — is what the job already uses, so a deployment
# that needs an sslmode keeps it. Copied from platformkit's scripts/mobile_e2e.sh
# with its reasoning: a PostgreSQL URL is scheme://user:pass@host:port/name with
# optional ?params, so the name is the last path segment and nothing else needs
# parsing.
swap() {
  python3 - "$1" "$2" <<'SWAP'
import sys

url, name = sys.argv[1], sys.argv[2]
head, _, query = url.partition("?")
if "://" not in head or "/" not in head.split("://", 1)[1]:
    print("mobile_ci: invalid PostgreSQL URL", file=sys.stderr)
    sys.exit(1)
cut = head.rindex("/")
sys.stdout.write(head[:cut] + "/" + name + (("?" + query) if query else ""))
SWAP
}
psql_admin() { psql "$(swap "$admin_url" postgres)" -v ON_ERROR_STOP=1 -q "$@"; }

work="$(mktemp -d)"
app_pid=""
leftover=""
created=false
cleanup() {
  status=$?
  if [ -n "$app_pid" ]; then
    kill "$app_pid" 2>/dev/null || true
    wait "$app_pid" 2>/dev/null || true
  fi
  if [ -n "$leftover" ]; then docker rm "$leftover" >/dev/null 2>&1 || true; fi
  if $created; then
    psql_admin -c "DROP DATABASE $database WITH (FORCE);" >/dev/null ||
      echo "mobile_ci: could not remove $database" >&2
  fi
  rm -rf "$work"
  return "$status"
}
trap cleanup EXIT

echo "mobile_ci: the kernel the job named, by digest"
if ! docker pull "$image" >/dev/null; then
  echo "mobile_ci: the runner cannot pull $image. Either the registry needs credentials this job does not carry or the image has to be mirrored where the runner reaches it." >&2
  exit 1
fi
leftover=$(docker create "$image")
docker cp "$leftover:/platformkit" "$work/platformkit"
docker rm "$leftover" >/dev/null
leftover=""
chmod +x "$work/platformkit"

echo "mobile_ci: a database of its own"
psql_admin -c "CREATE DATABASE $database;" >/dev/null
created=true
# The role exists (scripts/e2e/postgres-role.sql made it); the grants are per
# database, so a fresh one needs them again.
psql "$(swap "$admin_url" "$database")" -v ON_ERROR_STOP=1 -q \
  -c "GRANT USAGE ON SCHEMA public TO platformkit_app;" \
  -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO platformkit_app;" \
  -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO platformkit_app;"

app_dsn="$(swap "$app_url" "$database")"
migrate_dsn="$(swap "$admin_url" "$database")"
cat >"$work/config.yaml" <<YAML
server:
  addr: ":$port"
  public_host: "localhost:$port"
  docs: false
database:
  url: "$app_dsn"
  migrate_url: "$migrate_dsn"
nats:
  url: "${PLATFORMKIT_TEST_NATS_URL:-nats://localhost:4222}"
log:
  level: "warn"
audit:
  retention_days: 365
files:
  dir: "$work/files"
YAML

password="mobile-$(date +%s)-password"
# The device reaches the server through run.sh's `adb reverse` below, so the
# address it is told to talk to is the device's own localhost. --language is the
# tenant's own declaration, as the kernel harness writes it: a tenant created
# without a second language is served in one. The copy a phone shows comes from
# the device's locale, not this value, so the English-speaking flows are
# unaffected by it either way.
run_app() {
  for variable in "${!PLATFORMKIT_@}"; do unset "$variable"; done
  export PLATFORMKIT_BOOTSTRAP_PASSWORD="$password"
  exec "$work/platformkit" "$@"
}
echo "mobile_ci: one tenant and one administrator"
(run_app bootstrap --config "$work/config.yaml" \
  --tenant e2e --host localhost --name "End to end" --admin-email admin@e2e.test \
  --language pt-PT) >/dev/null

if command -v ss >/dev/null && ss -ltn 2>/dev/null | grep -q ":$port "; then
  echo "mobile_ci: something is already listening on $port; set PLATFORMKIT_MOBILE_PORT." >&2
  exit 1
fi

echo "mobile_ci: serving on $port"
run_app run --config "$work/config.yaml" >"$work/app.log" 2>&1 &
app_pid=$!
for _ in $(seq 1 60); do
  if curl -fsS "http://localhost:$port/health" >/dev/null 2>&1; then break; fi
  if ! kill -0 "$app_pid" 2>/dev/null; then
    echo "mobile_ci: the server stopped before it served:" >&2
    cat "$work/app.log" >&2
    exit 1
  fi
  sleep 1
done

# One contract, both runners: what this script invents it exports, and what the
# job names arrives in the environment it was named in. TITLE stays run.sh's to
# default, so a re-run of one flow alone still lands on a stamped record name.
export SERVER="http://localhost:$port" EMAIL="admin@e2e.test" PASSWORD="$password"
scripts/e2e/run.sh "$apk"

echo "mobile_ci: the journeys ran; the report is at $PK_MOBILE_REPORT"
