// Generation is offline and deterministic. Missing, changed and extra output,
// or fixture bytes no longer vouched for by provenance, are refusals, not fixes.
import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { compare, generate, verifySource } from "../scripts/api";

test("two generations agree and every class of generated drift is refused without repair", async () => {
  const temporary = await mkdtemp(join(tmpdir(), "api-generation-"));
  try {
    const first = join(temporary, "first");
    const second = join(temporary, "second");
    await generate(process.cwd(), first);
    await generate(process.cwd(), second);
    await compare(first, second);
    const file = join(second, "types.gen.ts");
    const original = await readFile(file);
    await writeFile(file, "// changed\n");
    await assert.rejects(compare(first, second), /types.gen.ts: generated bytes differ/);
    assert.equal(await readFile(file, "utf8"), "// changed\n");
    await rm(file);
    await assert.rejects(compare(first, second), /types.gen.ts: missing or extra/);
    await writeFile(file, original);
    await writeFile(join(second, "obsolete.ts"), "// stale\n");
    await assert.rejects(compare(first, second), /obsolete.ts: missing or extra/);
    const root = join(temporary, "fixture");
    await mkdir(join(root, "testdata"), { recursive: true });
    for (const name of ["openapi.json", "openapi.source.json"])
      await cp(join("testdata", name), join(root, "testdata", name));
    await verifySource(root);
    await writeFile(join(root, "testdata/openapi.json"), "{}\n");
    await assert.rejects(verifySource(root), /provenance SHA-256 mismatch/);
  } finally {
    await rm(temporary, { recursive: true, force: true });
  }
});
