// Generated by scripts/tokens.ts from testdata/design-tokens.json; run npm run tokens. Do not edit.
// Values come from the application's design export, so a phone and a browser
// read the same product.

export type Mode = "light" | "dark";

export interface Palette {
  readonly surfaceCanvas: string;
  readonly surfacePrimary: string;
  readonly surfaceMuted: string;
  readonly textPrimary: string;
  readonly textMuted: string;
  readonly borderDefault: string;
  readonly borderStrong: string;
  readonly accentDefault: string;
  readonly accentHover: string;
  readonly accentOn: string;
  readonly focus: string;
  readonly statusOk: string;
  readonly statusOkBg: string;
  readonly statusWarning: string;
  readonly statusWarningBg: string;
  readonly statusDanger: string;
  readonly statusDangerBg: string;
  readonly statusInfo: string;
  readonly statusInfoBg: string;
  readonly sidebarBg: string;
  readonly sidebarText: string;
  readonly sidebarMuted: string;
}

export const palette: Readonly<Record<Mode, Palette>> = {
  light: {
    surfaceCanvas: "#f2efe7",
    surfacePrimary: "#fffdf7",
    surfaceMuted: "#e9e4d8",
    textPrimary: "#15221f",
    textMuted: "#5f6b65",
    borderDefault: "#cbc5b8",
    borderStrong: "#8f988f",
    accentDefault: "#0f5d4e",
    accentHover: "#0a493e",
    accentOn: "#f9fff9",
    focus: "#326de6",
    statusOk: "#12715d",
    statusOkBg: "#dcf3e8",
    statusWarning: "#9a5318",
    statusWarningBg: "#fff0d2",
    statusDanger: "#9e3833",
    statusDangerBg: "#fbe5e2",
    statusInfo: "#2455c4",
    statusInfoBg: "#e5ecfa",
    sidebarBg: "#12201d",
    sidebarText: "#eff4e9",
    sidebarMuted: "#aebbb2",
  },
  dark: {
    surfaceCanvas: "#0e1614",
    surfacePrimary: "#151f1d",
    surfaceMuted: "#1e2a27",
    textPrimary: "#eef3ec",
    textMuted: "#a3b0aa",
    borderDefault: "#2c3b37",
    borderStrong: "#5c6d67",
    accentDefault: "#4bbf9c",
    accentHover: "#68d3b2",
    accentOn: "#08201a",
    focus: "#7aa2ff",
    statusOk: "#5fd0ac",
    statusOkBg: "#12312a",
    statusWarning: "#e0a955",
    statusWarningBg: "#33240f",
    statusDanger: "#f0918a",
    statusDangerBg: "#3a1d1b",
    statusInfo: "#8fb0f5",
    statusInfoBg: "#18244a",
    sidebarBg: "#0a1210",
    sidebarText: "#eff4e9",
    sidebarMuted: "#8b9a93",
  },
};

/** fontStacks are the export's CSS fallback stacks, as data; theme.tsx picks the native face. */
export const fontStacks = {
  display: '"Iowan Old Style", "Palatino Linotype", Palatino, Georgia, serif',
  body: '"IBM Plex Sans", Aptos, "Helvetica Neue", sans-serif',
  mono: '"IBM Plex Mono", "SFMono-Regular", Consolas, monospace',
} as const;
