// System words shared by the composed kit. Product nouns remain supplied content.
export const kitEnglish = {
  by: "by",
  activityEmpty: "Nothing has happened to this record yet.",
  actions: "Actions",
  clear: "Clear",
  close: "Close",
  open: "Open",
  select: "Select",
  selected: "Selected",
  unavailable: "No longer available. Choose again or refresh.",
  allLoaded: "Select loaded items",
  loaded: "loaded",
  of: "of",
  selection: "Selection",
  filters: "Filters",
  moreFilters: "More filters",
  sort: "Sort",
  views: "Saved views",
  unsaved: "Unsaved changes",
  expand: "Expand",
  collapse: "Collapse",
  more: "Load more",
  summary: "Summary",
  details: "Full details",
  activity: "Activity",
  system: "the system",
  unknownActor: "Unknown actor",
  before: "Before",
  after: "After",
  missing: "Not supplied",
  redacted: "Redacted",
  excluded: "This account’s plan does not include the activity trail.",
  older: "Show older",
  back: "Back",
  next: "Next",
  skip: "Skip",
  finish: "Finish",
  complete: "Complete",
  skipped: "Skipped",
  required: "Required",
  optional: "Optional",
  saveExit: "Save and exit",
  steps: "Steps",
  validation: "Review the highlighted fields.",
  available: "Available",
  soldOut: "Sold out",
  full: "Not enough places",
  booked: "Booked",
  closed: "Closed",
  past: "Already started",
  expired: "This availability has expired. Refresh it.",
  unknownCapacity: "Capacity unknown",
  capacity: "Places remaining",
  refresh: "Refresh",
  today: "Today",
  previous: "Previous",
  day: "Day",
  week: "Week",
  agenda: "Agenda",
  allDay: "All day",
  continues: "Continues",
  moreEvents: "More events",
  // Seven days do not fit a phone's column, so the week is drawn sideways. The row
  // says so, because a column that ends mid-Tuesday reads as a broken table rather
  // than as the first part of a week.
  weekSideways: "Swipe sideways for the rest of the week",
  noEvents: "No events",
  estimate: "Estimate",
  price: "Price",
  quantity: "Quantity",
  increase: "Increase",
  decrease: "Decrease",
  remove: "Remove",
  subtotal: "Subtotal",
  adjustments: "Adjustments",
  total: "Total",
  quoteExpired: "Request a fresh quote.",
  receipt: "Receipt",
  quote: "Quote",
  current: "Current plan",
  recommended: "Recommended",
  period: "Billing period",
  included: "Included",
  notIncluded: "Not included",
  unknown: "Unknown",
  map: "Map",
  list: "List",
  legend: "Legend",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  panLeft: "Pan left",
  panRight: "Pan right",
  panUp: "Pan up",
  panDown: "Pan down",
  reset: "Reset",
  unsupportedLocation: "This location is outside the map projection.",
  points: "Locations",
  images: "Images",
  imageUnavailable: "Image unavailable",
  retryImage: "Reload image",
  table: "Data table",
  // What a plot says before its numbers: the one observation a person came to
  // read. The axis supplies the rest of the sentence.
  peak: "Peak",
  range: "Range",
  noSamples: "No samples",
  noBaseline: "No baseline",
  unchanged: "Unchanged",
  favorable: "Favourable",
  unfavorable: "Unfavourable",
  step: "Step",
  unmeasured: "No total to measure against",
  left: "left",
  play: "Play",
  pause: "Pause",
  rewind: "Rewind",
  skipAhead: "Skip ahead",
  search: "Search",
  results: "results",
  clearSearch: "Clear search",
  cancelSearch: "Cancel search",
  searching: "Searching",
  navigate: "Navigate",
  cancel: "Cancel",
  dismiss: "Dismiss",
  // The words a specimen is made of. A gallery that said only "Example", "First"
  // and "Second" showed controls and no task, so the kit's specimens speak of one
  // visit to one place: a pass bought, the rooms it opens, when it is used. These
  // are the gallery's own fixture, named in both languages and read through here
  // like every other word: no screen, case or rule branches on them, and no
  // consumer of the kit is named by them.
  specimenPass: "Riverside Gallery annual pass",
  choosePlan: "Choose this pass",
  benefitTours: "Guided tour of the print room",
  variantIndividual: "Individual",
  variantTwoAdults: "Two adults",
  stepDetails: "Your details",
  stepVisit: "Visit time",
  photoPrintRoom: "The print room in morning light",
  photoCourtyard: "The courtyard from the upper landing",
  placePrintRoom: "Print room",
  placeCourtyard: "Courtyard",
  seriesVisitors: "Visitors per hour",
  seriesPassesSold: "Passes sold",
  axisHour: "Hour of day",
  axisVisitors: "Visitors",
  unitVisitors: "visitors",
  unitPasses: "passes",
  axisVariant: "Pass",
  seriesChange: "Change in passes on last week",
  seriesCourtyard: "Visitors in the courtyard",
  meterStorage: "Storage used",
  detailBody: "Admits two adults to the print room and the courtyard. Show it at either entrance.",
  detailAdmission: "Admits",
  detailVisitors: "For",
  queryPrint: "print room",
  nowPlaying: "Now playing",
  periodMonthly: "Monthly",
  periodAnnual: "Annual",
  // An amount owed on a schedule says what it is charged in, or it is not a
  // commitment anyone can check: 12.99 monthly and 12.99 yearly are the same
  // four figures and two different promises.
  unitMonthly: "per month",
  unitYearly: "per year",
  sourceFloorPlan: "Gallery floor plan",
  audioTour: "Audio tour",
} as const;
export type KitWords = { readonly [K in keyof typeof kitEnglish]: string };
export const kitPortuguese: KitWords = {
  by: "por",
  activityEmpty: "Ainda nada aconteceu a este registo.",
  actions: "Ações",
  clear: "Limpar",
  close: "Fechar",
  open: "Abrir",
  select: "Selecionar",
  selected: "Selecionado",
  unavailable: "Já não está disponível. Escolha novamente ou atualize.",
  allLoaded: "Selecionar itens carregados",
  loaded: "carregados",
  of: "de",
  selection: "Seleção",
  filters: "Filtros",
  moreFilters: "Mais filtros",
  sort: "Ordenação",
  views: "Vistas guardadas",
  unsaved: "Alterações por guardar",
  expand: "Expandir",
  collapse: "Recolher",
  more: "Carregar mais",
  summary: "Resumo",
  details: "Detalhes completos",
  activity: "Atividade",
  system: "O sistema",
  unknownActor: "Autor desconhecido",
  before: "Antes",
  after: "Depois",
  missing: "Não fornecido",
  redacted: "Ocultado",
  excluded: "Esta conta não inclui o histórico de atividade.",
  older: "Mostrar anteriores",
  back: "Voltar",
  next: "Seguinte",
  skip: "Saltar",
  finish: "Concluir",
  complete: "Concluído",
  skipped: "Saltado",
  required: "Obrigatório",
  optional: "Opcional",
  saveExit: "Guardar e sair",
  steps: "Etapas",
  validation: "Reveja os campos assinalados.",
  available: "Disponível",
  soldOut: "Esgotado",
  full: "Lugares insuficientes",
  booked: "Reservado",
  closed: "Fechado",
  past: "Já começou",
  expired: "Esta disponibilidade expirou. Atualize-a.",
  unknownCapacity: "Capacidade desconhecida",
  capacity: "Lugares disponíveis",
  refresh: "Atualizar",
  today: "Hoje",
  previous: "Anterior",
  day: "Dia",
  week: "Semana",
  agenda: "Agenda",
  allDay: "Todo o dia",
  continues: "Continua",
  moreEvents: "Mais eventos",
  weekSideways: "Deslize para o lado para ver o resto da semana",
  noEvents: "Sem eventos",
  estimate: "Estimativa",
  price: "Preço",
  quantity: "Quantidade",
  increase: "Aumentar",
  decrease: "Diminuir",
  remove: "Remover",
  subtotal: "Subtotal",
  adjustments: "Ajustes",
  total: "Total",
  quoteExpired: "Peça uma nova cotação.",
  receipt: "Recibo",
  quote: "Cotação",
  current: "Plano atual",
  recommended: "Recomendado",
  period: "Período de faturação",
  included: "Incluído",
  notIncluded: "Não incluído",
  unknown: "Desconhecido",
  map: "Mapa",
  list: "Lista",
  legend: "Legenda",
  zoomIn: "Ampliar",
  zoomOut: "Reduzir",
  panLeft: "Mover para a esquerda",
  panRight: "Mover para a direita",
  panUp: "Mover para cima",
  panDown: "Mover para baixo",
  reset: "Repor",
  unsupportedLocation: "Esta localização está fora da projeção do mapa.",
  points: "Localizações",
  images: "Imagens",
  imageUnavailable: "Imagem indisponível",
  retryImage: "Recarregar imagem",
  table: "Tabela de dados",
  peak: "Pico",
  range: "Intervalo",
  noSamples: "Sem amostras",
  noBaseline: "Sem referência",
  unchanged: "Sem alteração",
  favorable: "Favorável",
  unfavorable: "Desfavorável",
  step: "Etapa",
  unmeasured: "Sem total para medir",
  left: "restante",
  play: "Reproduzir",
  pause: "Pausar",
  rewind: "Retroceder",
  skipAhead: "Avançar",
  search: "Pesquisar",
  results: "resultados",
  clearSearch: "Limpar pesquisa",
  cancelSearch: "Cancelar pesquisa",
  searching: "A pesquisar",
  navigate: "Navegar",
  cancel: "Cancelar",
  dismiss: "Dispensar",
  specimenPass: "Passe anual da Galeria do Rio",
  choosePlan: "Escolher este bilhete",
  benefitTours: "Visita guiada à sala de gravuras",
  variantIndividual: "Individual",
  variantTwoAdults: "Dois adultos",
  stepDetails: "Os seus dados",
  stepVisit: "Hora da visita",
  photoPrintRoom: "A sala de gravuras com a luz da manhã",
  photoCourtyard: "O pátio visto do patamar de cima",
  placePrintRoom: "Sala de gravuras",
  placeCourtyard: "Pátio",
  seriesVisitors: "Visitantes por hora",
  seriesPassesSold: "Passes vendidos",
  axisHour: "Hora do dia",
  axisVisitors: "Visitantes",
  unitVisitors: "visitantes",
  unitPasses: "passes",
  axisVariant: "Passe",
  seriesChange: "Variação de passes face à semana passada",
  seriesCourtyard: "Visitantes no pátio",
  meterStorage: "Armazenamento usado",
  detailBody: "Admite dois adultos à sala de gravuras e ao pátio. Mostre-o em qualquer entrada.",
  detailAdmission: "Admite a",
  detailVisitors: "Para",
  queryPrint: "sala de gravuras",
  nowPlaying: "A tocar",
  periodMonthly: "Mensal",
  periodAnnual: "Anual",
  unitMonthly: "por mês",
  unitYearly: "por ano",
  sourceFloorPlan: "Planta do piso da galeria",
  audioTour: "Audioguia",
};
