// System words shared by the composed kit. Product nouns remain supplied content.
export const kitEnglish = {
  by: "by",
  activityEmpty: "Nothing has happened to this record yet.",
  actions: "Actions",
  clear: "Clear",
  close: "Close",
  open: "Open",
  select: "Select",
  selected: "Selected",
  unavailable: "No longer available. Choose again or refresh.",
  allLoaded: "Select loaded items",
  loaded: "loaded",
  of: "of",
  selection: "Selection",
  filters: "Filters",
  moreFilters: "More filters",
  sort: "Sort",
  views: "Saved views",
  unsaved: "Unsaved changes",
  expand: "Expand",
  collapse: "Collapse",
  more: "Load more",
  summary: "Summary",
  details: "Full details",
  activity: "Activity",
  system: "the system",
  unknownActor: "Unknown actor",
  before: "Before",
  after: "After",
  missing: "Not supplied",
  redacted: "Redacted",
  excluded: "This account’s plan does not include the activity trail.",
  older: "Show older",
  back: "Back",
  next: "Next",
  skip: "Skip",
  finish: "Finish",
  complete: "Complete",
  skipped: "Skipped",
  required: "Required",
  saveExit: "Save and exit",
  steps: "Steps",
  validation: "Review the highlighted fields.",
  available: "Available",
  full: "Not enough places",
  booked: "Booked",
  closed: "Closed",
  past: "Already started",
  expired: "This availability has expired. Refresh it.",
  unknownCapacity: "Capacity unknown",
  capacity: "Places remaining",
  refresh: "Refresh",
  today: "Today",
  previous: "Previous",
  day: "Day",
  week: "Week",
  agenda: "Agenda",
  allDay: "All day",
  continues: "Continues",
  moreEvents: "More events",
  noEvents: "No events",
  estimate: "Estimate",
  price: "Price",
  quantity: "Quantity",
  increase: "Increase",
  decrease: "Decrease",
  remove: "Remove",
  subtotal: "Subtotal",
  adjustments: "Adjustments",
  total: "Total",
  quoteExpired: "Request a fresh quote.",
  receipt: "Receipt",
  quote: "Quote",
  current: "Current plan",
  recommended: "Recommended",
  period: "Billing period",
  included: "Included",
  notIncluded: "Not included",
  unknown: "Unknown",
  map: "Map",
  list: "List",
  legend: "Legend",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  reset: "Reset",
  unsupportedLocation: "This location is outside the map projection.",
  points: "Locations",
  images: "Images",
  imageUnavailable: "Image unavailable",
  retryImage: "Reload image",
  table: "Data table",
  range: "Range",
  noSamples: "No samples",
  noBaseline: "No baseline",
  unchanged: "Unchanged",
  favorable: "Favourable",
  unfavorable: "Unfavourable",
} as const;
export type KitWords = { readonly [K in keyof typeof kitEnglish]: string };
export const kitPortuguese: KitWords = {
  by: "por",
  activityEmpty: "Ainda nada aconteceu a este registo.",
  actions: "Ações",
  clear: "Limpar",
  close: "Fechar",
  open: "Abrir",
  select: "Selecionar",
  selected: "Selecionado",
  unavailable: "Já não está disponível. Escolha novamente ou atualize.",
  allLoaded: "Selecionar itens carregados",
  loaded: "carregados",
  of: "de",
  selection: "Seleção",
  filters: "Filtros",
  moreFilters: "Mais filtros",
  sort: "Ordenação",
  views: "Vistas guardadas",
  unsaved: "Alterações por guardar",
  expand: "Expandir",
  collapse: "Recolher",
  more: "Carregar mais",
  summary: "Resumo",
  details: "Detalhes completos",
  activity: "Atividade",
  system: "O sistema",
  unknownActor: "Autor desconhecido",
  before: "Antes",
  after: "Depois",
  missing: "Não fornecido",
  redacted: "Ocultado",
  excluded: "Esta conta não inclui o histórico de atividade.",
  older: "Mostrar anteriores",
  back: "Voltar",
  next: "Seguinte",
  skip: "Saltar",
  finish: "Concluir",
  complete: "Concluído",
  skipped: "Saltado",
  required: "Obrigatório",
  saveExit: "Guardar e sair",
  steps: "Etapas",
  validation: "Reveja os campos assinalados.",
  available: "Disponível",
  full: "Lugares insuficientes",
  booked: "Reservado",
  closed: "Fechado",
  past: "Já começou",
  expired: "Esta disponibilidade expirou. Atualize-a.",
  unknownCapacity: "Capacidade desconhecida",
  capacity: "Lugares disponíveis",
  refresh: "Atualizar",
  today: "Hoje",
  previous: "Anterior",
  day: "Dia",
  week: "Semana",
  agenda: "Agenda",
  allDay: "Todo o dia",
  continues: "Continua",
  moreEvents: "Mais eventos",
  noEvents: "Sem eventos",
  estimate: "Estimativa",
  price: "Preço",
  quantity: "Quantidade",
  increase: "Aumentar",
  decrease: "Diminuir",
  remove: "Remover",
  subtotal: "Subtotal",
  adjustments: "Ajustes",
  total: "Total",
  quoteExpired: "Peça uma nova cotação.",
  receipt: "Recibo",
  quote: "Cotação",
  current: "Plano atual",
  recommended: "Recomendado",
  period: "Período de faturação",
  included: "Incluído",
  notIncluded: "Não incluído",
  unknown: "Desconhecido",
  map: "Mapa",
  list: "Lista",
  legend: "Legenda",
  zoomIn: "Ampliar",
  zoomOut: "Reduzir",
  reset: "Repor",
  unsupportedLocation: "Esta localização está fora da projeção do mapa.",
  points: "Localizações",
  images: "Imagens",
  imageUnavailable: "Imagem indisponível",
  retryImage: "Recarregar imagem",
  table: "Tabela de dados",
  range: "Intervalo",
  noSamples: "Sem amostras",
  noBaseline: "Sem referência",
  unchanged: "Sem alteração",
  favorable: "Favorável",
  unfavorable: "Desfavorável",
};
