// System words shared by the composed kit. Product nouns remain supplied content.
export const kitEnglish = {
  by: "by",
  activityEmpty: "Nothing has happened to this record yet.",
  actions: "Actions",
  clear: "Clear",
  close: "Close",
  open: "Open",
  select: "Select",
  selected: "Selected",
  unavailable: "No longer available. Choose again or refresh.",
  // A catalogue entry may name a screen this build does not hold. The generic
  // screens still draw the record, so this is the app saying it is behind, not a
  // refusal — quiet, one line, and the only thing said about it.
  shellUpdate: "Update the app for this record's full screen.",
  // What the first screen says about the session: the address the person signed in
  // at is the workspace's name until a name exists, the account under it is the
  // person's own words, and a row that opens nothing is said to be read alone.
  workspace: "Workspace",
  readOnly: "Read only",
  // A record whose schema names nothing to read as its title. The noun arrives
  // from the catalogue, the way `failure.loadFailed` takes one: this is the only
  // sentence the kit writes for a record it cannot name, and it is written once.
  untitled: (singular: string) => `Untitled ${singular}`,
  // A record's own words: the block that holds what the entry filed nowhere, the
  // collapsed section that holds what a record keeps about itself rather than about
  // its subject, and the three parts of the disclosure that opens it. `reveals` is a
  // noun phrase because `disclosure.reveal` builds the sentence around it.
  overview: "Overview",
  recordInformation: "Record information",
  recordInformationHolds: "The record’s identifier and the moments it changed.",
  recordInformationContent: "the identifier and the timestamps",
  // What a trail calls a person whose name the directory does not hold. Never the id:
  // a user id on a screen is a fact about the store, quoted to a person who cannot
  // look anything up with it.
  nameUnavailable: "Name unavailable",
  // A delete, asked in the words 0085 sets down: the record by its own name, the
  // warning plain, and an answer that names what it does. "Permanently" is not
  // claimed: a soft-deleting resource is recoverable by an administrator.
  deleteQuestion: (title: string) => `Delete ‘${title}’?`,
  deleteWarning: "You can’t undo this in the app.",
  deleteAction: (singular: string) => `Delete ${singular}`,
  moreOptions: "More options",
  justNow: "Just now",
  // The distances a time is read as, spelled by the kit where the engine has no Intl.RelativeTimeFormat (Hermes on
  // Android). They say what Intl says in each language, so a phone and a test read the same words.
  minuteAgo: "1 minute ago",
  minutesAgo: "{n} minutes ago",
  hourAgo: "1 hour ago",
  hoursAgo: "{n} hours ago",
  yesterday: "yesterday",
  twoDaysAgo: "2 days ago",
  daysAgo: "{n} days ago",
  tomorrow: "tomorrow",
  signInIntro: "Enter your workspace address and the email you use there.",
  workspaceAddress: "Workspace address",
  allLoaded: "Select loaded items",
  of: "of",
  selection: "Selection",
  filters: "Filters",
  moreFilters: "More filters",
  sort: "Sort",
  // The bar under the header that holds both doors. It is named for itself: the
  // accessible name of a group of controls that repeated one of its own buttons
  // would tell a reader the bar *is* that button.
  listControls: "List controls",
  // A filter group always answers, so the choice that narrows nothing is "All", the
  // reading of the group, and never "Clear", which is what a reset at the group's edge
  // is called (`clear` above stays that word's owner).
  all: "All",
  clearFilters: "Clear filters",
  filtersActive: (count: string) => `Filters · ${count}`,
  // The two doors a list's toolbar holds. `new` is the header's word for a record of
  // no known kind; `newNamed` names the kind the catalogue gave it.
  new: "New",
  newNamed: (singular: string) => `New ${singular}`,
  // The other sheet's title. `new` names a record of no known kind, this names the
  // record a person opened their own sheet to change, in the words the catalogue
  // gave its resource: a header that said `Edit note` while the toolbar under it
  // said `New Note` was spelling one kind of thing two ways.
  editNamed: (singular: string) => `Edit ${singular}`,
  // The three answers an empty list gives, which are three different facts: nothing
  // has arrived yet, nothing arrived that matches, and nothing can arrive yet.
  emptyNone: (plural: string) => `No ${plural} yet`,
  emptyCreate: (singular: string) => `Create a ${singular} to get started.`,
  // The sentence opens with the noun, so it is capitalised here: this kit wrote the
  // fallback plural lower-case and a sentence may not begin with it. A declared name
  // arrives as its author wrote it, and capitalising what is already capitalised does
  // nothing.
  emptyArrive: (plural: string) =>
    `${plural.charAt(0).toUpperCase()}${plural.slice(1)} will appear here when they're available.`,
  noMatching: (plural: string) => `No matching ${plural}`,
  filteredBody: "Try another search or clear your filters.",
  // The direction words a sort sheet says. Which words a field takes is its type's,
  // so a phone never reads "ascending" for a deadline and never reads English at all.
  sortNewest: "Newest first",
  sortOldest: "Oldest first",
  sortAZ: (word: string) => `${word}, A–Z`,
  sortZA: (word: string) => `${word}, Z–A`,
  sortSoon: (word: string) => `${word}, soonest first`,
  sortLate: (word: string) => `${word}, latest first`,
  sortLow: (word: string) => `${word}, low to high`,
  sortHigh: (word: string) => `${word}, high to low`,
  views: "Saved views",
  unsaved: "Unsaved changes",
  expand: "Expand",
  collapse: "Collapse",
  more: "Load more",
  summary: "Summary",
  details: "Full details",
  // The two verbs that end a step someone is inside. A stepper's "Next" moves along
  // stages the person can already see; a card's or a cart's step leads to a screen
  // they cannot, so the word names the place.
  reviewSelection: "Review selection",
  reviewOrder: "Review order",
  activity: "Activity",
  system: "the system",
  unknownActor: "Unknown actor",
  before: "Before",
  after: "After",
  missing: "Not supplied",
  redacted: "Redacted",
  older: "Show older",
  back: "Back",
  next: "Next",
  skip: "Skip",
  finish: "Finish",
  complete: "Complete",
  skipped: "Skipped",
  required: "Required",
  optional: "Optional",
  // The tag box: one word for the act, one sentence to name whose list it is, one
  // to name which chip goes. A list stores its items comma-joined, so the box that
  // writes one item says so when a person types the separator. The field's own word
  // keeps the case its author gave it — one sentence, spelled one way, whether it is
  // the placeholder in the box or the name the box announces.
  addTag: "Add",
  addTagTo: (label: string) => `Add to ${label}`,
  removeTag: (tag: string) => `Remove ${tag}`,
  commaInValue: "Remove the comma from this value.",
  saveExit: "Save and exit",
  steps: "Steps",
  validation: "Review the highlighted fields.",
  available: "Available",
  soldOut: "Sold out",
  full: "Not enough places",
  booked: "Booked",
  closed: "Closed",
  past: "Already started",
  expired: "This availability has expired. Refresh it.",
  unknownCapacity: "Capacity unknown",
  capacity: "Places remaining",
  refresh: "Refresh",
  today: "Today",
  previous: "Previous",
  day: "Day",
  week: "Week",
  agenda: "Agenda",
  allDay: "All day",
  continues: "Continues",
  moreEvents: "More events",
  // Seven days do not fit a phone's column, so the week is drawn sideways. The row
  // says so, because a column that ends mid-Tuesday reads as a broken table rather
  // than as the first part of a week.
  weekSideways: "Swipe sideways for the rest of the week",
  noEvents: "No events",
  estimate: "Estimate",
  price: "Price",
  quantity: "Quantity",
  increase: "Increase",
  decrease: "Decrease",
  remove: "Remove",
  subtotal: "Subtotal",
  adjustments: "Adjustments",
  total: "Total",
  quoteExpired: "Request a fresh quote.",
  receipt: "Receipt",
  quote: "Quote",
  current: "Current plan",
  recommended: "Recommended",
  period: "Billing period",
  included: "Included",
  notIncluded: "Not included",
  unknown: "Unknown",
  map: "Map",
  list: "List",
  legend: "Legend",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  panLeft: "Pan left",
  panRight: "Pan right",
  panUp: "Pan up",
  panDown: "Pan down",
  reset: "Reset",
  unsupportedLocation: "This location is outside the map projection.",
  points: "Locations",
  images: "Images",
  imageUnavailable: "Image unavailable",
  retryImage: "Reload image",
  table: "Data table",
  // What a plot says before its numbers: the one observation a person came to
  // read. The axis supplies the rest of the sentence.
  peak: "Peak",
  range: "Range",
  noSamples: "No samples",
  noBaseline: "No baseline",
  unchanged: "Unchanged",
  favorable: "Favourable",
  unfavorable: "Unfavourable",
  step: "Step",
  unmeasured: "No total to measure against",
  left: "left",
  play: "Play",
  pause: "Pause",
  rewind: "Rewind",
  skipAhead: "Skip ahead",
  search: "Search",
  results: "results",
  clearSearch: "Clear search",
  cancelSearch: "Cancel search",
  searching: "Searching",
  navigate: "Navigate",
  cancel: "Cancel",
  dismiss: "Dismiss",
  // The words a specimen is made of. A gallery that said only "Example", "First"
  // and "Second" showed controls and no task, so the kit's specimens speak of one
  // visit to one place: a pass bought, the rooms it opens, when it is used. These
  // are the gallery's own fixture, named in both languages and read through here
  // like every other word: no screen, case or rule branches on them, and no
  // consumer of the kit is named by them.
  specimenPass: "Riverside Gallery annual pass",
  /** specimenGroup names a collection by what it holds. A group that takes the name
   * of one of its own members says the same words twice on the same screen. */
  specimenGroup: "Pass options",
  benefitTours: "Guided tour of the print room",
  variantIndividual: "Individual",
  variantTwoAdults: "Two adults",
  stepDetails: "Your details",
  stepVisit: "Visit time",
  photoPrintRoom: "The print room in morning light",
  photoCourtyard: "The courtyard from the upper landing",
  placePrintRoom: "Print room",
  placeCourtyard: "Courtyard",
  seriesVisitors: "Visitors per hour",
  seriesPassesSold: "Passes sold",
  axisHour: "Hour of day",
  axisVisitors: "Visitors",
  unitVisitors: "visitors",
  unitPasses: "passes",
  axisVariant: "Pass",
  seriesChange: "Change in passes on last week",
  seriesCourtyard: "Visitors in the courtyard",
  meterStorage: "Storage used",
  detailBody: "Admits two adults to the print room and the courtyard. Show it at either entrance.",
  detailAdmission: "Admits",
  detailVisitors: "For",
  queryPrint: "print room",
  nowPlaying: "Now playing",
  periodMonthly: "Monthly",
  periodAnnual: "Annual",
  // An amount owed on a schedule says what it is charged in, or it is not a
  // commitment anyone can check: 12.99 monthly and 12.99 yearly are the same
  // four figures and two different promises.
  unitMonthly: "per month",
  unitYearly: "per year",
  sourceFloorPlan: "Gallery floor plan",
  audioTour: "Audio tour",
} as const;
// Each word keeps its own shape, widened from the literal it is written as: most
// are strings, and the few that take a noun as data (`untitled`) are functions
// here exactly as they are in the table. A flat `string` for every key would
// force the noun-taking ones back into English.
type KitWord<T> = T extends string ? string : T;
export type KitWords = { readonly [K in keyof typeof kitEnglish]: KitWord<(typeof kitEnglish)[K]> };
export const kitPortuguese: KitWords = {
  by: "por",
  activityEmpty: "Ainda nada aconteceu a este registo.",
  actions: "Ações",
  clear: "Limpar",
  close: "Fechar",
  open: "Abrir",
  select: "Selecionar",
  selected: "Selecionado",
  unavailable: "Já não está disponível. Escolha novamente ou atualize.",
  shellUpdate: "Atualize a aplicação para o ecrã completo deste registo.",
  workspace: "Espaço de trabalho",
  readOnly: "Apenas leitura",
  untitled: (singular: string) => `${singular} sem título`,
  overview: "Visão geral",
  recordInformation: "Informações do registo",
  recordInformationHolds: "O identificador do registo e os momentos em que mudou.",
  recordInformationContent: "o identificador e as datas",
  nameUnavailable: "Nome indisponível",
  deleteQuestion: (title: string) => `Eliminar ‘${title}’?`,
  deleteWarning: "Não é possível anular esta ação na aplicação.",
  deleteAction: (singular: string) => `Eliminar ${singular}`,
  moreOptions: "Mais opções",
  justNow: "Agora mesmo",
  minuteAgo: "há 1 minuto",
  minutesAgo: "há {n} minutos",
  hourAgo: "há 1 hora",
  hoursAgo: "há {n} horas",
  yesterday: "ontem",
  twoDaysAgo: "anteontem",
  daysAgo: "há {n} dias",
  tomorrow: "amanhã",
  signInIntro: "Indique o endereço do espaço de trabalho e o email que usa nele.",
  workspaceAddress: "Endereço do espaço de trabalho",
  allLoaded: "Selecionar itens carregados",
  of: "de",
  selection: "Seleção",
  filters: "Filtros",
  moreFilters: "Mais filtros",
  sort: "Ordenação",
  listControls: "Controles da lista",
  all: "Todos",
  clearFilters: "Limpar filtros",
  filtersActive: (count: string) => `Filtros · ${count}`,
  new: "Novo",
  newNamed: (singular: string) => `Novo ${singular}`,
  editNamed: (singular: string) => `Editar ${singular}`,
  emptyNone: (plural: string) => `Ainda não há ${plural}`,
  emptyCreate: (singular: string) => `Crie um ${singular} para começar.`,
  emptyArrive: (plural: string) => `Os ${plural} aparecem aqui quando estão disponíveis.`,
  noMatching: (plural: string) => `Nenhum ${plural} corresponde`,
  filteredBody: "Experimente outra pesquisa ou limpe os filtros.",
  sortNewest: "Mais recentes primeiro",
  sortOldest: "Mais antigos primeiro",
  sortAZ: (word: string) => `${word}, A–Z`,
  sortZA: (word: string) => `${word}, Z–A`,
  sortSoon: (word: string) => `${word}, mais próximo primeiro`,
  sortLate: (word: string) => `${word}, mais distante primeiro`,
  sortLow: (word: string) => `${word}, crescente`,
  sortHigh: (word: string) => `${word}, decrescente`,
  views: "Vistas guardadas",
  unsaved: "Alterações por guardar",
  expand: "Expandir",
  collapse: "Recolher",
  more: "Carregar mais",
  summary: "Resumo",
  details: "Detalhes completos",
  reviewSelection: "Revisar a seleção",
  reviewOrder: "Revisar o pedido",
  activity: "Atividade",
  system: "O sistema",
  unknownActor: "Autor desconhecido",
  before: "Antes",
  after: "Depois",
  missing: "Não fornecido",
  redacted: "Ocultado",
  older: "Mostrar anteriores",
  back: "Voltar",
  next: "Seguinte",
  skip: "Saltar",
  finish: "Concluir",
  complete: "Concluído",
  skipped: "Saltado",
  required: "Obrigatório",
  optional: "Opcional",
  addTag: "Adicionar",
  addTagTo: (label: string) => `Adicionar a ${label}`,
  removeTag: (tag: string) => `Remover ${tag}`,
  commaInValue: "Remova a vírgula deste valor.",
  saveExit: "Guardar e sair",
  steps: "Etapas",
  validation: "Reveja os campos assinalados.",
  available: "Disponível",
  soldOut: "Esgotado",
  full: "Lugares insuficientes",
  booked: "Reservado",
  closed: "Fechado",
  past: "Já começou",
  expired: "Esta disponibilidade expirou. Atualize-a.",
  unknownCapacity: "Capacidade desconhecida",
  capacity: "Lugares disponíveis",
  refresh: "Atualizar",
  today: "Hoje",
  previous: "Anterior",
  day: "Dia",
  week: "Semana",
  agenda: "Agenda",
  allDay: "Todo o dia",
  continues: "Continua",
  moreEvents: "Mais eventos",
  weekSideways: "Deslize para o lado para ver o resto da semana",
  noEvents: "Sem eventos",
  estimate: "Estimativa",
  price: "Preço",
  quantity: "Quantidade",
  increase: "Aumentar",
  decrease: "Diminuir",
  remove: "Remover",
  subtotal: "Subtotal",
  adjustments: "Ajustes",
  total: "Total",
  quoteExpired: "Peça uma nova cotação.",
  receipt: "Recibo",
  quote: "Cotação",
  current: "Plano atual",
  recommended: "Recomendado",
  period: "Período de faturação",
  included: "Incluído",
  notIncluded: "Não incluído",
  unknown: "Desconhecido",
  map: "Mapa",
  list: "Lista",
  legend: "Legenda",
  zoomIn: "Ampliar",
  zoomOut: "Reduzir",
  panLeft: "Mover para a esquerda",
  panRight: "Mover para a direita",
  panUp: "Mover para cima",
  panDown: "Mover para baixo",
  reset: "Repor",
  unsupportedLocation: "Esta localização está fora da projeção do mapa.",
  points: "Localizações",
  images: "Imagens",
  imageUnavailable: "Imagem indisponível",
  retryImage: "Recarregar imagem",
  table: "Tabela de dados",
  peak: "Pico",
  range: "Intervalo",
  noSamples: "Sem amostras",
  noBaseline: "Sem referência",
  unchanged: "Sem alteração",
  favorable: "Favorável",
  unfavorable: "Desfavorável",
  step: "Etapa",
  unmeasured: "Sem total para medir",
  left: "restante",
  play: "Reproduzir",
  pause: "Pausar",
  rewind: "Retroceder",
  skipAhead: "Avançar",
  search: "Pesquisar",
  results: "resultados",
  clearSearch: "Limpar pesquisa",
  cancelSearch: "Cancelar pesquisa",
  searching: "A pesquisar",
  navigate: "Navegar",
  cancel: "Cancelar",
  dismiss: "Dispensar",
  specimenPass: "Passe anual da Galeria do Rio",
  specimenGroup: "Opções de passe",
  benefitTours: "Visita guiada à sala de gravuras",
  variantIndividual: "Individual",
  variantTwoAdults: "Dois adultos",
  stepDetails: "Os seus dados",
  stepVisit: "Hora da visita",
  photoPrintRoom: "A sala de gravuras com a luz da manhã",
  photoCourtyard: "O pátio visto do patamar de cima",
  placePrintRoom: "Sala de gravuras",
  placeCourtyard: "Pátio",
  seriesVisitors: "Visitantes por hora",
  seriesPassesSold: "Passes vendidos",
  axisHour: "Hora do dia",
  axisVisitors: "Visitantes",
  unitVisitors: "visitantes",
  unitPasses: "passes",
  axisVariant: "Passe",
  seriesChange: "Variação de passes face à semana passada",
  seriesCourtyard: "Visitantes no pátio",
  meterStorage: "Armazenamento usado",
  detailBody: "Admite dois adultos à sala de gravuras e ao pátio. Mostre-o em qualquer entrada.",
  detailAdmission: "Admite a",
  detailVisitors: "Para",
  queryPrint: "sala de gravuras",
  nowPlaying: "A tocar",
  periodMonthly: "Mensal",
  periodAnnual: "Anual",
  unitMonthly: "por mês",
  unitYearly: "por ano",
  sourceFloorPlan: "Planta do piso da galeria",
  audioTour: "Audioguia",
};
